import ASSETS from './assets.js';

export default {
    'warrior_idle': {
        key: 'warrior_idle',
        texture: ASSETS.spritesheet.warrior_idle.key,
        frameRate: 8,
        repeat: -1,
        config: { start: 0, end: 7 },
    },
    'warrior_run': {
        key: 'warrior_run',
        texture: ASSETS.spritesheet.warrior_run.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 5 },
    },
    'warrior_attack1': {
        key: 'warrior_attack1',
        texture: ASSETS.spritesheet.warrior_attack1.key,
        frameRate: 14,
        repeat: 0,
        config: { start: 0, end: 3 },
    },
    'warrior_attack2': {
        key: 'warrior_attack2',
        texture: ASSETS.spritesheet.warrior_attack2.key,
        frameRate: 14,
        repeat: 0,
        config: { start: 0, end: 3 },
    },
    'pawn_idle': {
        key: 'pawn_idle',
        texture: ASSETS.spritesheet.pawn_idle.key,
        frameRate: 8,
        repeat: -1,
        config: { start: 0, end: 7 },
    },
    'pawn_run': {
        key: 'pawn_run',
        texture: ASSETS.spritesheet.pawn_run.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 5 },
    },
    'archer_idle': {
        key: 'archer_idle',
        texture: ASSETS.spritesheet.archer_idle.key,
        frameRate: 8,
        repeat: -1,
        config: { start: 0, end: 5 },
    },
    'archer_run': {
        key: 'archer_run',
        texture: ASSETS.spritesheet.archer_run.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 3 },
    },
    'archer_shoot': {
        key: 'archer_shoot',
        texture: ASSETS.spritesheet.archer_shoot.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 7 },
    },
    'arrow': {
        key: 'arrow',
        texture: ASSETS.spritesheet.arrow.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 0 },
    },
    'monk_idle': {
        key: 'monk_idle',
        texture: ASSETS.spritesheet.monk_idle.key,
        frameRate: 8,
        repeat: -1,
        config: { start: 0, end: 5 },
    },
    'monk_run': {
        key: 'monk_run',
        texture: ASSETS.spritesheet.monk_run.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 3 },
    },
    'monk_heal': {
        key: 'monk_heal',
        texture: ASSETS.spritesheet.monk_heal.key,
        frameRate: 10,
        repeat: 0,
        config: { start: 0, end: 10 },
    },
    'heal_effect': {
        key: 'heal_effect',
        texture: ASSETS.spritesheet.heal_effect.key,
        frameRate: 10,
        repeat: 0,
        config: { start: 0, end: 10 },
    },
    'lancer_idle': {
        key: 'lancer_idle',
        texture: ASSETS.spritesheet.lancer_idle.key,
        frameRate: 8,
        repeat: -1,
        config: { start: 0, end: 11 },
    },
    'lancer_run': {
        key: 'lancer_run',
        texture: ASSETS.spritesheet.lancer_run.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 5 },
    },
    'lancer_attack': {
        key: 'lancer_attack',
        texture: ASSETS.spritesheet.lancer_attack.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 2 },
    },
    'explosion_01': {
        key: 'explosion_01',
        texture: ASSETS.spritesheet.explosion_01.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 7 },
    },
    'explosion_02': {
        key: 'explosion_02',
        texture: ASSETS.spritesheet.explosion_02.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 9 },
    },
    'fire_01': {
        key: 'fire_01',
        texture: ASSETS.spritesheet.fire_01.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 7 },
    },
    'fire_02': {
        key: 'fire_02',
        texture: ASSETS.spritesheet.fire_02.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 9 },
    },
    'fire_03': {
        key: 'fire_03',
        texture: ASSETS.spritesheet.fire_03.key,
        frameRate: 10,
        repeat: -1,
        config: { start: 0, end: 11 },
    },
    'dust_01': {
        key: 'dust_01',
        texture: ASSETS.spritesheet.dust_01.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 7 },
    },
    'dust_02': {
        key: 'dust_02',
        texture: ASSETS.spritesheet.dust_02.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 9 },
    },
    'water_splash': {
        key: 'water_splash',
        texture: ASSETS.spritesheet.water_splash.key,
        frameRate: 12,
        repeat: 0,
        config: { start: 0, end: 8 },
    },
};